name: Build C App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile launcher
        run: |
          clang -arch arm64 -o launcher C/launcher.c
          chmod +x launcher

      - name: Create zip
        run: |
          zip -r App-Build.zip launcher

      - name: Upload launcher zip
        uses: actions/upload-artifact@v4
        with:
          name: App-Build
          path: App-Build.zip