name: Build Windows GUI EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # checkout은 v4 가능

      - name: Set up MSYS2 for GCC
        uses: msys2/setup-msys2@v2  # 여기만 v2로 변경
        with:
          update: true

      - name: Build GUI EXE
        run: |
          mkdir build
          gcc C/dummy.c -o build/dummy.exe -mwindows

      - name: Upload build artifact as ZIP
        uses: actions/upload-artifact@v3  # upload-artifact 최신은 v3
        with:
          name: dummy-gui-exe
          path: build/dummy.exe
          retention-days: 1
